### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by abhishek-compro** [bhch/django-jsonform#91]
The following is screenshot from dark mode:

![image](https://user-images.githubusercontent.com/106737446/219269793-44049c0a-9fbd-4c5d-87ce-b5db4d9f6c98.png)

You can see that the text in the yellow background is hardly visible.

**Comment by bhch** [comment]
Thank you for reporting. I'll fix it in the next release.

Until then you can override the bg colour in your custom CSS:

```css
.rjf-form-row-controls:hover + .rjf-form-row-inner,
.rjf-form-row-controls:hover + .rjf-form-group {
    background-color: <value-here>
}
```
